### ISSUE TITLE
Settings for video tools

### ISSUE THREAD

**Issue by ByteBrewer** [snuailab/waffle_utils#22]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar feature requests.

### Description

- Add `Settings` for common parameters used in different scripts and methods
- Add attributes for supported fomats of video and image

### Use case

Define the settings at separate script
```python
# settings.py

# Default parameters
DEFAULT_FRAME_RATE = 30
 
# Supported format
SUPPORTED_VIDEO_FORMAT = [".avi", ".mp4"]
SUPPORTED_IMAGE_FORAMT = [".jpg", ".png"]
```
Use the default setting
```python
# run.py

from settings import DEFAULT_FRAME_RATE
from waffle.utils.video.tools import extract_frames

extract_frames(input_path, output_dir, DEFAULT_FRAME_RATE)
```
Check the supported file format
```python
# tools.py

from settings import SUPPORTED_VIDEO_FORMAT

def extract_frames(input_path, output_dir, frame_rate):
    
    video = load_video(input_path)
    if video not in SUPPORTED_VIDEO_FORMAT:
        rasie ValueError("This video type is not supported")
```

**Comment by ZeroAct** [comment]
this issue should be resolved at #28 PR together
