### ISSUE TITLE
Need to import existing split sets

### ISSUE THREAD

**Issue by ZeroAct** [snuailab/waffle_utils#45]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar feature requests.

### Description

- import splitted dataset

**Comment by oneQuery** [comment]
Can you specify how the splitted dataset look like? Is it like this?
```
# for mnist dataset as an example
mnist/
    ├ images/
    │   ├ train/
    │   ├ val/
    │   └ test/
    └ coco.json
```
