### ISSUE TITLE
Dataset Export - Dataset Format 자동선택 기능

### ISSUE THREAD

**Issue by pmz-q** [snuailab/waffle_utils#57]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar feature requests.

### Description

Dataset.export 에 waffle hub 에서 선택 가능한 model type 을 입력 할 경우, export dataset format 이 자동선택 될 수 있으면 좋을 것 같습니다.
- waffle hub 와 waffle utils 가 서로 연동 가능하다고 생각합니다
- 만일 waffle hub train 에서 사용하는 dataset 의 format 이 각 model type 별 정해져있다면 model type 에 대한 정보를 waffle dataset export 가 알면 좋을 것 같습니다
- 혹은 waffle hub 가 supported dataset format 을 갖고 있어도 상관 없습니다.
- mapping 가능한...

**Comment by ZeroAct** [comment]
@snuailab/waffle We should add task to Dataset.
